

CREATE TABLE NguoiDung (
    id INT AUTO_INCREMENT PRIMARY KEY,
    hoVaTen VARCHAR(100) NOT NULL,
    tenDangNhap VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    matKhau VARCHAR(255) NOT NULL,
    gioiTinh ENUM('Nam', 'Nu', 'Khac') NOT NULL,
    vaiTro ENUM('HocSinh', 'GiaoVien') NOT NULL,
    ngayTao TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;


CREATE TABLE LopHoc (
    id INT AUTO_INCREMENT PRIMARY KEY,
    tenLop VARCHAR(100) NOT NULL,
    maLop VARCHAR(10) NOT NULL UNIQUE,
    idGiaoVien INT NOT NULL,
    ngayTao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (idGiaoVien) REFERENCES NguoiDung(id) ON DELETE CASCADE
) ENGINE=InnoDB;


CREATE TABLE ThanhVienLop (
    idHocSinh INT NOT NULL,
    idLop INT NOT NULL,
    ngayThamGia TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (idHocSinh, idLop),
    FOREIGN KEY (idHocSinh) REFERENCES NguoiDung(id) ON DELETE CASCADE,
    FOREIGN KEY (idLop) REFERENCES LopHoc(id) ON DELETE CASCADE
) ENGINE=InnoDB;


CREATE TABLE NganHangCauHoi (
    id INT AUTO_INCREMENT PRIMARY KEY,
    noiDung TEXT NOT NULL,
    loaiCauHoi ENUM('TracNghiem', 'DungSaiNhieuY', 'TraLoiNgan') NOT NULL,
    idGiaoVien INT NOT NULL,
    ngayTao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (idGiaoVien) REFERENCES NguoiDung(id) ON DELETE CASCADE
) ENGINE=InnoDB;


CREATE TABLE PhuongAn (
    id INT AUTO_INCREMENT PRIMARY KEY,
    idCauHoi INT NOT NULL,
    noiDung TEXT NOT NULL,
    laDapAnDung BOOLEAN NOT NULL DEFAULT FALSE,
    FOREIGN KEY (idCauHoi) REFERENCES NganHangCauHoi(id) ON DELETE CASCADE
) ENGINE=InnoDB;


CREATE TABLE BaiKiemTra (
    id INT AUTO_INCREMENT PRIMARY KEY,
    tenBaiKiemTra VARCHAR(255) NOT NULL,
    thongTin TEXT,
    thoiGianLamBai INT NOT NULL, -- tính bằng phút
    matKhau VARCHAR(255) NULL,
    soLanLamBaiToiDa INT NOT NULL DEFAULT 1, -- Số lần làm bài tối đa
    idLop INT NOT NULL,
    idGiaoVien INT NOT NULL,
    ngayTao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (idLop) REFERENCES LopHoc(id) ON DELETE CASCADE,
    FOREIGN KEY (idGiaoVien) REFERENCES NguoiDung(id) ON DELETE CASCADE
) ENGINE=InnoDB;


CREATE TABLE ChiTietBaiKiemTra (
    idBaiKiemTra INT NOT NULL,
    idCauHoi INT NOT NULL,
    diem FLOAT NOT NULL,
    PRIMARY KEY (idBaiKiemTra, idCauHoi),
    FOREIGN KEY (idBaiKiemTra) REFERENCES BaiKiemTra(id) ON DELETE CASCADE,
    FOREIGN KEY (idCauHoi) REFERENCES NganHangCauHoi(id) ON DELETE CASCADE
) ENGINE=InnoDB;


CREATE TABLE KetQuaBaiKiemTra (
    id INT AUTO_INCREMENT PRIMARY KEY,
    idBaiKiemTra INT NOT NULL,
    idHocSinh INT NOT NULL,
    diemSo FLOAT NOT NULL,
    thoiGianNopBai TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    thoiGianBatDau DATETIME NOT NULL,
    FOREIGN KEY (idBaiKiemTra) REFERENCES BaiKiemTra(id) ON DELETE CASCADE,
    FOREIGN KEY (idHocSinh) REFERENCES NguoiDung(id) ON DELETE CASCADE
) ENGINE=InnoDB;


CREATE TABLE ChiTietBaiLam (
    idKetQua INT NOT NULL,
    idCauHoi INT NOT NULL,
    idPhuongAnDaChon INT NULL,
    traLoiNgan TEXT NULL,
    PRIMARY KEY (idKetQua, idCauHoi),
    FOREIGN KEY (idKetQua) REFERENCES KetQuaBaiKiemTra(id) ON DELETE CASCADE,
    FOREIGN KEY (idCauHoi) REFERENCES NganHangCauHoi(id) ON DELETE CASCADE,
    FOREIGN KEY (idPhuongAnDaChon) REFERENCES PhuongAn(id) ON DELETE SET NULL
) ENGINE=InnoDB;


CREATE TABLE TroChoiDHBC (
    id INT AUTO_INCREMENT PRIMARY KEY,
    tenTroChoi VARCHAR(255) NOT NULL,
    thoiGianChoi INT NULL, -- Thời gian tính bằng phút
    matKhau VARCHAR(255) NULL,
    idLop INT NOT NULL,
    idGiaoVien INT NOT NULL,
    ngayTao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (idLop) REFERENCES LopHoc(id) ON DELETE CASCADE,
    FOREIGN KEY (idGiaoVien) REFERENCES NguoiDung(id) ON DELETE CASCADE
) ENGINE=InnoDB;


CREATE TABLE CauHoiDHBC (
    id INT AUTO_INCREMENT PRIMARY KEY,
    idTroChoi INT NOT NULL,
    tenFileAnh VARCHAR(255) NOT NULL, -- Tên file ảnh đã được upload
    dapAn VARCHAR(255) NOT NULL,      -- Đáp án cho hình ảnh
    goiY TEXT NULL,                   -- Gợi ý (nếu có)
    FOREIGN KEY (idTroChoi) REFERENCES TroChoiDHBC(id) ON DELETE CASCADE
) ENGINE=InnoDB;


CREATE TABLE KetQuaDHBC (
    id INT AUTO_INCREMENT PRIMARY KEY,
    idTroChoi INT NOT NULL,
    idHocSinh INT NOT NULL,
    diemSo INT NOT NULL,
    thoiGianHoanThanh INT NULL, -- Thời gian hoàn thành tính bằng giây
    ngayChoi TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (idTroChoi) REFERENCES TroChoiDHBC(id) ON DELETE CASCADE,
    FOREIGN KEY (idHocSinh) REFERENCES NguoiDung(id) ON DELETE CASCADE
) ENGINE=InnoDB;